name: Build
on:
  workflow_dispatch:

jobs:
  json:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Retrieve release from GitHub, update all info
        run: ./update-formula.sh 
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update brew info"
          file_pattern: Info
